package timeline

import (
	"encoding/json"
	"os"
	"testing"
)

// TestDateKeysParity checks Go's ParseDate against the oracle's
// parseDateToken() for every token in testdata/date-keys.json, generated by
// scripts/parity/date-keys.mjs from the real vault's distinct tokens plus
// hand-picked edge cases (DESIGN.md §10.1).
func TestDateKeysParity(t *testing.T) {
	b, err := os.ReadFile("testdata/date-keys.json")
	if err != nil {
		t.Fatal(err)
	}
	var want map[string]*string
	if err := json.Unmarshal(b, &want); err != nil {
		t.Fatal(err)
	}
	if len(want) == 0 {
		t.Fatal("empty date-keys.json")
	}
	for token, wantKey := range want {
		got, ok := ParseDate(token)
		if wantKey == nil {
			if ok {
				t.Errorf("ParseDate(%q) = %q, want unparseable", token, got.Key)
			}
			continue
		}
		if !ok {
			t.Errorf("ParseDate(%q): unparseable, want key %q", token, *wantKey)
			continue
		}
		if got.Key != *wantKey {
			t.Errorf("ParseDate(%q).Key = %q, want %q", token, got.Key, *wantKey)
		}
	}
}

func TestParseDateForms(t *testing.T) {
	cases := []struct {
		raw       string
		wantKey   string
		wantFrom  string
		wantTo    string
		wantPrec  Precision
		wantValid bool
	}{
		{"2026-09-10/12", "2026-09-10", "2026-09-10", "2026-09-12", PrecDayRange, true},
		{"2026-08-2x", "2026-08-20", "2026-08-20", "2026-08-29", PrecDecade, true},
		{"2026-08-0x", "2026-08-00", "2026-08-01", "2026-08-09", PrecDecade, true},
		{"2021-02/03", "2021-02-00", "2021-02-01", "2021-03-31", PrecMonthRange, true},
		{"2026-09-10", "2026-09-10", "2026-09-10", "2026-09-10", PrecDay, true},
		{"2026-07", "2026-07-00", "2026-07-01", "2026-07-31", PrecMonth, true},
		{"2026-03 (heel maand)", "2026-03-00", "2026-03-01", "2026-03-31", PrecMonth, true},
	}
	for _, c := range cases {
		d, ok := ParseDate(c.raw)
		if !ok {
			t.Errorf("ParseDate(%q): unparseable", c.raw)
			continue
		}
		if d.Key != c.wantKey || d.From != c.wantFrom || d.To != c.wantTo || d.Precision != c.wantPrec {
			t.Errorf("ParseDate(%q) = %+v, want key=%s from=%s to=%s prec=%s",
				c.raw, d, c.wantKey, c.wantFrom, c.wantTo, c.wantPrec)
		}
		if d.Valid() != c.wantValid {
			t.Errorf("ParseDate(%q).Valid() = %v, want %v", c.raw, d.Valid(), c.wantValid)
		}
	}
}

func TestParseDateUnparseable(t *testing.T) {
	for _, raw := range []string{"juli/augustus 2026", "", "not a date", "2026"} {
		if _, ok := ParseDate(raw); ok {
			t.Errorf("ParseDate(%q): expected unparseable", raw)
		}
	}
}

func TestDateValidity(t *testing.T) {
	if d, _ := ParseDate("2026-02-30"); d.Valid() {
		t.Error("2026-02-30 should be invalid (day precision, real calendar check)")
	}
	if d, _ := ParseDate("2026-13-01"); d.Valid() {
		t.Error("2026-13-01 should be invalid (month 13)")
	}
	if d, _ := ParseDate("2026-13"); d.Valid() {
		t.Error("2026-13 (month-only) should be invalid (month 13)")
	}
	if d, _ := ParseDate("2026-12-31"); !d.Valid() {
		t.Error("2026-12-31 should be valid")
	}
}

func TestOnOrAfter(t *testing.T) {
	month, _ := ParseDate("2026-08")
	if !month.OnOrAfter("2026-08-01") {
		t.Error("2026-08 should match --since 2026-08-01")
	}
	if !month.OnOrAfter("2026-08-15") {
		t.Error("2026-08 should match --since 2026-08-15")
	}
	july, _ := ParseDate("2026-07")
	if july.OnOrAfter("2026-08-01") {
		t.Error("2026-07 should not match --since 2026-08-01")
	}
}
